### Get all images.  Each request **MUST** be delimited by a triple hash
# This is a comment
GET http://localhost:3000/api/images

### A second example.  Each request **MUST** be delimited by a triple hash
POST http://localhost:3000/api/test
Content-Type: application/json # Content-Type header is a must if you're sending JSON
# Request body separated from headers by newline

{ "a": 1, "b": 2 }
### Get one image
GET http://localhost:3000/api/images/69aa6052d7ef8bc85b66a827


### General working
PUT http://localhost:3000/api/images/69aa6052d7ef8bc85b66a827/rename
Content-Type: application/json

{
    "newName": "Miguels image"
}

### Invalid new nam
PUT http://localhost:3000/api/images/69aa6052d7ef8bc85b66a827/rename
Content-Type: application/json

{
    "newName": ""
}

### 100 characters
PUT http://localhost:3000/api/images/69aa6052d7ef8bc85b66a827/rename
Content-Type: application/json

{
    "newName": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
}
### incorrent Image id an image
PUT http://localhost:3000/api/images/userId/rename
Content-Type: application/json

{

    "newName": "Miguels image"
}
### Register a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "testuser",
    "email": "test@example.com",
    "password": "password"
}
### Login
POST http://localhost:3000/api/auth/tokens
Content-Type: application/json

{
    "username": "testuser",
    "password": "password"
}

### Should get 401 - no token
GET http://localhost:3000/api/images

### Should work - with token
GET http://localhost:3000/api/images
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNzczNTMwNzc4LCJleHAiOjE3NzM2MTcxNzh9.3vGDcnVBs69Kuc0gq1vDobfr3yY_NpZHO_GNqu5J09k
